### ISSUE TITLE
QE issue

### ISSUE THREAD

**Issue by sunt05** [gusbacos/SuPy---Testing#1]
need to explain the large QE at Wisley

![image](https://user-images.githubusercontent.com/1802656/104578545-c3f74000-5652-11eb-8a55-a7a6c4915fd7.png)

**Comment by sunt05** [comment]
This might just be due to the site characteristics at Wisley.

Take July of 2011 for example, we can see similar available energy across different configurations 
(note the legend: *f for forcing, while s for site; and WS: Wisley; KC: Kings*; so `fWS_sKC` means `WS forcing applied to site KC`):
 
![image](https://user-images.githubusercontent.com/1802656/104582316-a082c400-5657-11eb-915f-f0626b61ec4e.png)



but remarkably different land cover fractions, where Wisley is dominated by vegetated surfaces (notably grass):

|       |   KC |   KC_WS |    WS |
|:------|-----:|--------:|------:|
| Bldgs | 0.43 |    0.43 | 0.001 |
| Paved | 0.38 |    0.38 | 0.002 |
| DecTr | 0    |    0    | 0.01  |
| EveTr | 0.02 |    0.02 | 0.05  |
| Grass | 0.03 |    0.03 | 0.927 |
| BSoil | 0    |    0    | 0.01  |
| Water | 0.14 |    0.14 | 0     |

**Comment by biglimp** [comment]
But what about the days in July 2012 that we looks at yesterday?

**Comment by sunt05** [comment]
I forgot to mention: situation of July of 2012 is very similar to what we see above.

![image](https://user-images.githubusercontent.com/1802656/104592915-dbd8bf00-5666-11eb-9c8e-ca93ac02bcbe.png)

**Comment by biglimp** [comment]
So the issue with negative Qh is no more?

**Comment by sunt05** [comment]
It is still there:

![image](https://user-images.githubusercontent.com/1802656/104593420-98328500-5667-11eb-936f-bc97b90712f8.png)
